In [1]:
# required libraries
import pandas as pd
import requests
from bs4 import BeautifulSoup
import numpy as np
from time import sleep
from random import randint

In [2]:
url = 'https://www.imdb.com/search/title/?groups=top_1000&sort=user_rating,desc&count=100&start'
response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser') # to get the content of the webpage in html format

In [3]:
response

In [4]:
#create empty list to store extracted data
movie_name = []
year = []
rating = []
time = []
metascore = []
votes = []
gross = []
description = []
director = []
stars = []

In [5]:
#creating an array of values for dynamic webpage
pages = np.arange(1,1000,100)

In [6]:
for page in pages:
    page = response
    soups = soup
    movie_data = soup.findAll('div', attrs = {'class': 'lister-item mode-advanced'})
    sleep(randint(2,8))
    
    for store in movie_data:
        name = store.h3.a.text
        movie_name.append(name)
        
        release_year = store.h3.find('span', class_ = "lister-item-year text-muted unbold").text
        year.append(release_year)
        
        runtime = store.p.find("span", class_ = 'runtime').text
        time.append(runtime)
        
        rate = store.find('div', class_ = "inline-block ratings-imdb-rating").text.replace('\n', '')
        rating.append(rate)
        
        score = store.find('span', class_ = "metascore").text if store.find('span', class_ = "metascore") else "^^^^"
        metascore.append(score)
        
        
        value = store.find_all('span', attrs = {'name': "nv"})
        
        vote = value[0].text
        votes.append(vote)
        
        gross_value = value[1].text if len(value)>1 else '$$$$'
        gross.append(gross_value)
         
        describe = store.find_all('p', class_ = 'text-muted')
        describe1 = describe[1].text.replace('\n', '') if len(describe) >1 else '####'
        description.append(describe1)
        
        cast = store.find("p", class_ = '')
        cast = cast.text.replace('\n', '').split('|')
        cast = [x.strip() for x in cast]
        cast = [cast[i].replace(j, "") for i,j in enumerate(["Director:", "Stars:"])]
        director.append(cast[0])
        stars.append([x.strip() for x in cast[1].split(",")])

In [7]:
# Create data frame
df_movie = pd.DataFrame({'Name of movie': movie_name, 'Release year': year, 'Runtime': time, 'Movie Rating': rating, 'Metascore': metascore, 'Votes': votes, 'Gross': gross, 'Description': description, 'Director': director, 'Star': stars})

In [8]:
#save as csv file
df_movie.to_csv('Data Scrapping Multiple Pages on IMDb.csv', index=False)

In [9]:
# save as Excel file
df_movie.to_excel('Data Scrapping Multiple Pages on IMDb.xlsx')

In [10]:
df_movie.head(30)

,Name of movie,Release year,Runtime,Movie Rating,Metascore,Votes,Gross,Description,Director,Star
0,The Shawshank Redemption,(1994),142 min,9.3,82,"2,808,716",$28.34M,"Over the course of several years, two convicts...",Frank Darabont,"[Tim Robbins, Morgan Freeman, Bob Gunton, Will..."
1,The Godfather,(1972),175 min,9.2,100,"1,957,317",$134.97M,"Don Vito Corleone, head of a mafia family, dec...",Francis Ford Coppola,"[Marlon Brando, Al Pacino, James Caan, Diane K..."
2,The Dark Knight,(2008),152 min,9.0,84,"2,790,417",$534.86M,When the menace known as the Joker wreaks havo...,Christopher Nolan,"[Christian Bale, Heath Ledger, Aaron Eckhart, ..."
3,Schindler's List,(1993),195 min,9.0,95,"1,411,942",$96.90M,"In German-occupied Poland during World War II,...",Steven Spielberg,"[Liam Neeson, Ralph Fiennes, Ben Kingsley, Car..."
4,The Lord of the Rings: The Return of the King,(2003),201 min,9.0,94,"1,922,701",$377.85M,Gandalf and Aragorn lead the World of Men agai...,Peter Jackson,"[Elijah Wood, Viggo Mortensen, Ian McKellen, O..."
5,12 Angry Men,(1957),96 min,9.0,97,"836,060",$4.36M,The jury in a New York City murder trial is fr...,Sidney Lumet,"[Henry Fonda, Lee J. Cobb, Martin Balsam, John..."
6,The Godfather Part II,(1974),202 min,9.0,90,"1,329,083",$57.30M,The early life and career of Vito Corleone in ...,Francis Ford Coppola,"[Al Pacino, Robert De Niro, Robert Duvall, Dia..."
7,Pulp Fiction,(1994),154 min,8.9,95,"2,154,027",$107.93M,"The lives of two mob hitmen, a boxer, a gangst...",Quentin Tarantino,"[John Travolta, Uma Thurman, Samuel L. Jackson..."
8,Fight Club,(1999),139 min,8.8,67,"2,243,076",$37.03M,An insomniac office worker and a devil-may-car...,David Fincher,"[Brad Pitt, Edward Norton, Meat Loaf, Zach Gre..."
9,Inception,(2010),148 min,8.8,74,"2,476,625",$292.58M,A thief who steals corporate secrets through t...,Christopher Nolan,"[Leonardo DiCaprio, Joseph Gordon-Levitt, Elli..."
10,The Lord of the Rings: The Fellowship of the Ring,(2001),178 min,8.8,92,"1,950,859",$315.54M,A meek Hobbit from the Shire and eight compani...,Peter Jackson,"[Elijah Wood, Ian McKellen, Orlando Bloom, Sea..."
11,Forrest Gump,(1994),142 min,8.8,82,"2,186,421",$330.25M,The history of the United States from the 1950...,Robert Zemeckis,"[Tom Hanks, Robin Wright, Gary Sinise, Sally F..."
12,"The Good, the Bad and the Ugly",(1966),148 min,8.8,90,"791,736",$6.10M,A bounty hunting scam joins two men in an unea...,Sergio Leone,"[Clint Eastwood, Eli Wallach, Lee Van Cleef, A..."
13,The Lord of the Rings: The Two Towers,(2002),179 min,8.8,87,"1,734,809",$342.55M,While Frodo and Sam edge closer to Mordor with...,Peter Jackson,"[Elijah Wood, Ian McKellen, Viggo Mortensen, O..."
14,Jai Bhim,(2021),164 min,8.8,^^^^,"211,105",#219,When a tribal man is arrested for a case of al...,T.J. Gnanavel,"[Suriya, Lijo Mol Jose, Manikandan K., Rajisha..."
15,777 Charlie,(2022),164 min,8.8,^^^^,"37,087",$$$$,Dharma is stuck in a rut with his negative and...,Kiranraj K,"[Rakshit Shetty, Charlie, Sangeetha Sringeri, ..."
16,Spider-Man: Across the Spider-Verse,(2023),140 min,8.7,86,"276,641",#22,"Miles Morales catapults across the Multiverse,...","Directors:Joaquim Dos Santos, Kemp Powers, Jus...","[Shameik Moore, Hailee Steinfeld, Brian Tyree ..."
17,Interstellar,(2014),169 min,8.7,74,"1,999,900",$188.02M,When Earth becomes uninhabitable in the future...,Christopher Nolan,"[Matthew McConaughey, Anne Hathaway, Jessica C..."
18,GoodFellas,(1990),145 min,8.7,92,"1,219,224",$46.84M,The story of Henry Hill and his life in the ma...,Martin Scorsese,"[Robert De Niro, Ray Liotta, Joe Pesci, Lorrai..."
19,The Matrix,(1999),136 min,8.7,73,"1,996,895",$171.48M,When a beautiful stranger leads computer hacke...,"Directors:Lana Wachowski, Lilly Wachowski","[Keanu Reeves, Laurence Fishburne, Carrie-Anne..."
20,One Flew Over the Cuckoo's Nest,(1975),133 min,8.7,84,"1,046,497",$112.00M,"In the Fall of 1963, a Korean War veteran and ...",Milos Forman,"[Jack Nicholson, Louise Fletcher, Michael Berr..."
21,Star Wars: Episode V - The Empire Strikes Back,(1980),124 min,8.7,82,"1,346,063",$290.48M,After the Rebels are overpowered by the Empire...,Irvin Kershner,"[Mark Hamill, Harrison Ford, Carrie Fisher, Bi..."
22,Rocketry: The Nambi Effect,(2022),157 min,8.7,^^^^,"55,732",$$$$,Based on the life of Indian Space Research Org...,Madhavan,"[Madhavan, Simran, Rajit Kapoor, Ravi Raghaven..."
23,Soorarai Pottru,(2020),153 min,8.7,^^^^,"121,109",$$$$,"Nedumaaran Rajangam ""Maara"" sets out to make t...",Sudha Kongara,"[Suriya, Paresh Rawal, Prakash Belawadi, Aparn..."
24,The Silence of the Lambs,(1991),118 min,8.6,86,"1,499,889",$130.74M,A young F.B.I. cadet must receive the help of ...,Jonathan Demme,"[Jodie Foster, Anthony Hopkins, Lawrence A. Bo..."
25,Seven,(1995),127 min,8.6,65,"1,740,483",$100.13M,"Two detectives, a rookie and a veteran, hunt a...",David Fincher,"[Morgan Freeman, Brad Pitt, Kevin Spacey, Andr..."
26,Saving Private Ryan,(1998),169 min,8.6,91,"1,454,815",$216.54M,"Following the Normandy Landings, a group of U....",Steven Spielberg,"[Tom Hanks, Matt Damon, Tom Sizemore, Edward B..."
27,Star Wars: Episode IV - A New Hope,(1977),121 min,8.6,90,"1,417,498",$322.74M,Luke Skywalker joins forces with a Jedi Knight...,George Lucas,"[Mark Hamill, Harrison Ford, Carrie Fisher, Al..."
28,The Green Mile,(1999),189 min,8.6,61,"1,365,611",$136.80M,"A tale set on death row in a Southern jail, wh...",Frank Darabont,"[Tom Hanks, Michael Clarke Duncan, David Morse..."
29,Terminator 2: Judgment Day,(1991),137 min,8.6,75,"1,145,109",$204.84M,"A cyborg, identical to the one who failed to k...",James Cameron,"[Arnold Schwarzenegger, Linda Hamilton, Edward..."

In [11]:
df_movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name of movie  1000 non-null   object
 1   Release year   1000 non-null   object
 2   Runtime        1000 non-null   object
 3   Movie Rating   1000 non-null   object
 4   Metascore      1000 non-null   object
 5   Votes          1000 non-null   object
 6   Gross          1000 non-null   object
 7   Description    1000 non-null   object
 8   Director       1000 non-null   object
 9   Star           1000 non-null   object
dtypes: object(10)
memory usage: 78.2+ KB

In [12]:
df_movie.describe()

,Name of movie,Release year,Runtime,Movie Rating,Metascore,Votes,Gross,Description,Director,Star
count,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000
unique,100,58,65,10,40,100,92,100,69,100
top,The Shawshank Redemption,(1994),164 min,8.4,^^^^,"2,808,716",$$$$,"Over the course of several years, two convicts...",Christopher Nolan,"[Tim Robbins, Morgan Freeman, Bob Gunton, Will..."
freq,10,50,40,310,120,10,90,10,70,10

In [13]:
df_movie.shape

(1000, 10)